services:
  # Base de datos MongoDB compartida para todos los servicios
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - microservices-network

  # Microservicio de Usuarios
  users-service:
    build:
      context: ./users-service
    container_name: users-service
    ports:
      - "3001:3001"
    depends_on:
      - mongodb
    environment:
      MONGO_URI: mongodb://mongodb:27017/petstore
      PORT: 3001
    networks:
      - microservices-network

  # Microservicio de Pedidos
  orders-service:
    build:
      context: ./orders-service
    container_name: orders-service
    ports:
      - "3003:3003"
    depends_on:
      - mongodb
    environment:
      MONGO_URI: mongodb://mongodb:27017/petstore
      PORT: 3003
    networks:
      - microservices-network

  # Microservicio de Productos
  products-service:
    build:
      context: ./products-service
    container_name: products-service
    ports:
      - "3004:3004"
    depends_on:
      - mongodb
    environment:
      MONGO_URI: mongodb://mongodb:27017/petstore
      PORT: 3004
    networks:
      - microservices-network

  # Microservicio de Carrito
  cart-service:
    build:
      context: ./cart-service
    container_name: cart-service
    ports:
      - "3005:3005"
    depends_on:
      - mongodb
    environment:
      MONGO_URI: mongodb://mongodb:27017/petstore
      PORT: 3005
    networks:
      - microservices-network

  #Microservicio de Reviews
  reviews-service:
    build:
      context: ./reviews-service
    container_name: reviews-service
    ports:
      - "3006:3006"
    depends_on:
      - mongodb
    environment:
      MONGO_URI: mongodb://mongodb:27017/petstore
      PORT: 3006
    networks:
      - microservices-network

  #Microservicio de Categorias
  categories-service:
    build:
      context: ./categories-service
    container_name: categories-service
    ports:
      - "3007:3007"
    depends_on:
      - mongodb
    environment:
      MONGO_URI: mongodb://mongodb:27017/petstore
      PORT: 3007
    networks:
      - microservices-network

  # API Gateway
  api-gateway:
    build:
      context: ./api_gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - users-service
      - orders-service
      - products-service
      - cart-service
    environment:
      USERS_SERVICE_URL: http://users-service:3001
      ORDERS_SERVICE_URL: http://orders-service:3003
      PRODUCTS_SERVICE_URL: http://products-service:3004
      CART_SERVICE_URL: http://cart-service:3005
      PORT: 8080
    networks:
      - microservices-network
    volumes:
      - ./api_gateway:/usr/src/app

volumes:
  mongo-data:

networks:
  microservices-network:
    driver: bridge
